# Name of your GitHub Actions workflow
name: CI Checks for Backend and Frontend

# Controls when the action will run
# This runs on pushes to the 'main' branch and on pull requests.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run in parallel
jobs:
  # This job checks the backend code
  backend-ci:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Sets up a Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Installs dependencies and runs the lint/test scripts if present
      - name: Install dependencies, lint and test (backend)
        run: |
          if [ -f backend/package.json ]; then
            echo "Found backend/package.json — running npm ci"
            cd backend
            npm ci
            echo "Available npm scripts:"
            npm run || true

            if npm run | grep -q " lint"; then
              echo "Running backend lint..."
              npm run lint
            else
              echo "No backend lint script defined, skipping."
            fi

            if npm run | grep -q " test"; then
              echo "Running backend tests..."
              npm test
            else
              echo "No backend test script defined, skipping."
            fi
          else
            echo "No backend/package.json found — skipping backend steps."
          fi

  # This job checks the frontend code
  frontend-ci:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Sets up a Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Installs dependencies and runs the build command
      - name: Install dependencies and build (frontend)
        run: |
          if [ -f exoplanet/frontend/package.json ]; then
            cd exoplanet/frontend
            npm ci
            if npm run | grep -q " build"; then
              npm run build
            else
              echo "No build script found in frontend/package.json, skipping build."
            fi
          else
            echo "No exoplanet/frontend/package.json found — skipping frontend steps."
          fi
